-- Migration 011: Add custom plot area bounding box fields
ALTER TABLE plots ADD COLUMN area_x1 INTEGER DEFAULT NULL;
ALTER TABLE plots ADD COLUMN area_y1 INTEGER DEFAULT NULL;
ALTER TABLE plots ADD COLUMN area_x2 INTEGER DEFAULT NULL;
ALTER TABLE plots ADD COLUMN area_y2 INTEGER DEFAULT NULL;
